// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvjgskohcdyhksabhrlo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2amdza29oY2R5aGtzYWJocmxvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NjUxNDIsImV4cCI6MjA2NjQ0MTE0Mn0.29hOS4UTAhDX4eZ0jqCQcfQ4eKJWxX7Nzzfr5Y7SuRg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);